server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/social_media

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: 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


idp:
  url: http://localhost:8180
  client-id: social_app
  client-secret: It9ar58VqpWG7ITE1EKsxsmYZ9EASeoI