# ??t tên cho ?ng d?ng
spring.application.name=database

# C?u hình k?t n?i MySQL
spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:28392/railway
spring.datasource.username=root
spring.datasource.password=adtNAazEmrHVitBdqZnwLyNhazObuWUm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (N?u dùng Hibernate ho?c Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
