server:
  port: 8081
  servlet:
    context-path: /profile


spring:
  application:
    name: profile-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/social_media

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

idp:
  url: http://localhost:8180
  client-id: social_app
  client-secret: It9ar58VqpWG7ITE1EKsxsmYZ9EASeoI

