server:
  port: 8081
  servlet:
    context-path: /profile


spring:
  application:
    name: profile-service

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/social_media
idp:
  url: http://localhost:8180
  client-id: social_app
  client-secret: It9ar58VqpWG7ITE1EKsxsmYZ9EASeoI

